"""Параметры реферальной программы."""

REFERRAL_WELCOME_DISCOUNT_PERCENT = 20
REFERRAL_WELCOME_BONUS_DAYS = 14
REFERRAL_PAYMENT_BONUS_DAYS = 5

REFERRAL_TIER_BASE_PERCENT = 10
REFERRAL_TIER_STEP_PERCENT = 5
REFERRAL_TIER_MAX_PERCENT = 30

REFERRAL_START_PREFIX = "ref_"

# Список приглашённых в экране «Реферальная программа»
REFERRAL_LIST_FETCH_LIMIT = 50